import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { useMCP } from '@/hooks/useMCP';
import { useSystemStatus } from './SystemStatusContext';
import { useActivityFeed } from './ActivityFeedContext';
import logger from '../lib/logger';

interface Explanation {
  layout: string;
  widgets: string;
  reasoning: string;
}

interface ExplainabilityContextType {
  explanation: Explanation | null;
  loading: boolean;
  error: string | null;
  refreshExplanation: () => void;
}

const defaultExplanation = {
  layout: 'This dashboard is designed as an agentic interface. The main panel provides at-a-glance status and control, while this panel offers transparency into the AI\'s reasoning, ensuring you\'re always in the loop.',
  widgets: 'The widgets on the left are displaying real-time data from your AI Homelab. The Predictive Actions are generated by an A2A agent analyzing the live event stream for opportunities and anomalies.',
  reasoning: 'Awaiting analysis of real-time data...'
}

export const ExplainabilityContext = createContext<ExplainabilityContextType>({
  explanation: defaultExplanation,
  loading: false,
  error: null,
  refreshExplanation: () => console.warn('ExplainabilityProvider not found'),
});

export const useExplainability = () => useContext(ExplainabilityContext);

export const ExplainabilityProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [explanation, setExplanation] = useState<Explanation | null>(defaultExplanation);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { kg_reason } = useMCP();
  const { services } = useSystemStatus();
  const { activities } = useActivityFeed();

  const generateExplanation = async () => {
    setLoading(true);
    setError(null);

    try {
      const systemContext = JSON.stringify(services);
      const activityContext = JSON.stringify(activities.slice(0, 5).map(a => a.message));
      const question = `Given the system status and recent activities, provide a JSON object with three keys: 'layout', 'widgets', and 'reasoning'. 'layout' should explain the dashboard's design philosophy. 'widgets' should explain what the user is seeing. 'reasoning' should provide a single, key insight based on the provided context.`;

      logger.info('[ExplainabilityContext] Generating explanation...');
      const response = await kg_reason({ question, context: `System Status: ${systemContext}\nRecent Activities: ${activityContext}` });
      logger.info('[ExplainabilityContext] Received explanation:', response);

      // Handle different response formats
      if (response) {
        // Handle both KGResponse format and mock format
        const responseText = 'result' in response ? response.result : 
                           'answer' in response ? response.answer : '';
        
        if (typeof responseText === 'string') {
          try {
            // Try parsing as JSON
            const parsed = JSON.parse(responseText);
            setExplanation({
              layout: parsed.layout || defaultExplanation.layout,
              widgets: parsed.widgets || defaultExplanation.widgets,
              reasoning: parsed.reasoning || defaultExplanation.reasoning,
            });
          } catch (parseError) {
            // Not valid JSON, use as reasoning only
            logger.warn('[ExplainabilityContext] Response not in JSON format, using as reasoning text');
            setExplanation({
              ...defaultExplanation,
              reasoning: responseText.substring(0, 500) // Limit length for safety
            });
          }
        } else if (typeof responseText === 'object') {
          // Handle object response
          const responseObj = responseText as any;
          setExplanation({
            layout: responseObj.layout || defaultExplanation.layout,
            widgets: responseObj.widgets || defaultExplanation.widgets,
            reasoning: responseObj.reasoning || defaultExplanation.reasoning,
          });
        } else {
          logger.warn('[ExplainabilityContext] Unexpected response format:', typeof responseText);
          setExplanation(defaultExplanation);
        }
      } else {
        // Empty or null response
        logger.warn('[ExplainabilityContext] Empty response from KG reasoning');
        setExplanation(defaultExplanation);
      }
    } catch (err: any) {
      logger.error('[ExplainabilityContext] Error generating explanation:', err);
      setError(err.message || 'Failed to generate explanation.');
      setExplanation(defaultExplanation);
    } finally {
      setLoading(false);
    }
  };

  // PERFORMANCE FIX: Disable automatic explanation generation to prevent slow navigation
  // Only generate explanations when explicitly requested
  // useEffect(() => {
  //   const timer = setTimeout(generateExplanation, 2000); // Initial delay to allow other contexts to load
  //   return () => clearTimeout(timer);
  // }, [services, activities]);

  const value = { explanation, loading, error, refreshExplanation: generateExplanation };

  return (
    <ExplainabilityContext.Provider value={value}>
      {children}
    </ExplainabilityContext.Provider>
  );
};
