/**
 * StaticChartBlock - Display static charts (PNG, SVG, JPG)
 * Phase 1: Basic chart display with metadata
 * Supports charts generated by Claude Code via matplotlib/seaborn
 */

'use client';

import React, { useState } from 'react';
import { useSemanticToken } from '@/hooks/useSemanticToken';
import {
  Box,
  Image,
  Text,
  HStack,
  VStack,
  IconButton,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalCloseButton,
  ModalBody,
  Tooltip,
  Badge,
  Button,
} from '@chakra-ui/react';
import {
  FiDownload,
  FiMaximize2,
  FiMoreVertical,
  FiRefreshCw,
  FiEdit,
  FiTrash2,
  FiBarChart2,
} from 'react-icons/fi';

export interface StaticChartBlockProps {
  blockId: string;
  imageUrl?: string;
  imageData?: string; // base64 encoded
  title?: string;
  caption?: string;
  altText?: string;
  metadata?: {
    chartLibrary?: string;
    chartType?: string;
    createdByAgent?: string;
    insights?: string[];
    status?: 'placeholder' | 'generated' | 'error';
    dimensions?: {
      width: number;
      height: number;
      dpi?: number;
    };
  };
  editable?: boolean;
  onRefresh?: () => void;
  onDelete?: () => void;
  onEdit?: () => void;
  onGenerate?: () => void;
}

export function StaticChartBlock({
  blockId,
  imageUrl,
  imageData,
  title,
  caption,
  altText,
  metadata,
  editable = false,
  onRefresh,
  onDelete,
  onEdit,
  onGenerate,
}: StaticChartBlockProps) {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [isHovered, setIsHovered] = useState(false);

  const bgColor = useSemanticToken('surface.elevated');
  const borderColor = useSemanticToken('border.default');
  const hoverBg = useSemanticToken('surface.hover');

  // Determine image source
  const imageSrc = imageData || imageUrl;

  const handleDownload = () => {
    if (!imageSrc) return;

    const link = document.createElement('a');
    link.href = imageSrc;
    link.download = `${title || 'chart'}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <>
      {/* Main Chart Block */}
      <Box
        position="relative"
        borderWidth="1px"
        borderColor={borderColor}
        borderRadius="md"
        overflow="hidden"
        bg={bgColor}
        transition="all 0.2s"
        _hover={{ borderColor: 'blue.400', bg: hoverBg }}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
        {/* Chart Header */}
        {(title || editable) && (
          <HStack
            px={4}
            py={2}
            borderBottomWidth="1px"
            borderColor={borderColor}
            justify="space-between"
          >
            <HStack spacing={2}>
              {title && (
                <Text fontWeight="semibold" fontSize="sm">
                  {title}
                </Text>
              )}
              {metadata?.createdByAgent === 'claude_code' && (
                <Badge colorScheme="purple" fontSize="xs">
                  AI Generated
                </Badge>
              )}
              {metadata?.chartLibrary && (
                <Badge colorScheme="gray" fontSize="xs">
                  {metadata.chartLibrary}
                </Badge>
              )}
            </HStack>

            {/* Action Buttons */}
            {editable && (
              <HStack spacing={1} opacity={isHovered ? 1 : 0} transition="opacity 0.2s">
                {onRefresh && (
                  <Tooltip label="Refresh data" placement="top">
                    <IconButton
                      aria-label="Refresh chart"
                      icon={<FiRefreshCw />}
                      size="sm"
                      variant="ghost"
                      onClick={onRefresh}
                    />
                  </Tooltip>
                )}

                <Tooltip label="View full size" placement="top">
                  <IconButton
                    aria-label="Expand"
                    icon={<FiMaximize2 />}
                    size="sm"
                    variant="ghost"
                    onClick={onOpen}
                  />
                </Tooltip>

                <Tooltip label="Download" placement="top">
                  <IconButton
                    aria-label="Download"
                    icon={<FiDownload />}
                    size="sm"
                    variant="ghost"
                    onClick={handleDownload}
                  />
                </Tooltip>

                <Menu>
                  <MenuButton
                    as={IconButton}
                    aria-label="More options"
                    icon={<FiMoreVertical />}
                    size="sm"
                    variant="ghost"
                  />
                  <MenuList>
                    {onEdit && (
                      <MenuItem icon={<FiEdit />} onClick={onEdit}>
                        Edit settings
                      </MenuItem>
                    )}
                    <MenuItem icon={<FiDownload />} onClick={handleDownload}>
                      Download PNG
                    </MenuItem>
                    {onDelete && (
                      <MenuItem icon={<FiTrash2 />} onClick={onDelete} color="red.500">
                        Delete chart
                      </MenuItem>
                    )}
                  </MenuList>
                </Menu>
              </HStack>
            )}
          </HStack>
        )}

        {/* Chart Image */}
        <Box p={4}>
          {imageSrc ? (
            <Image
              src={imageSrc}
              alt={altText || title || 'Chart visualization'}
              maxW="100%"
              height="auto"
              borderRadius="md"
              cursor="pointer"
              onClick={onOpen}
              loading="lazy"
            />
          ) : (
            <Box
              height="300px"
              display="flex"
              alignItems="center"
              justifyContent="center"
              bg={useSemanticToken('surface.base')}
              borderRadius="md"
              borderWidth="2px"
              borderStyle="dashed"
              borderColor={useSemanticToken('border.default')}
            >
              <VStack spacing={4}>
                <Box
                  p={4}
                  bg={useSemanticToken('surface.highlight')}
                  borderRadius="full"
                >
                  <FiBarChart2 size={32} color="#3182CE" />
                </Box>
                <VStack spacing={2}>
                  <Text fontWeight="semibold" color={useSemanticToken('text.primary')}>
                    {metadata?.status === 'placeholder' ? 'Chart Placeholder' : 'No Chart Data'}
                  </Text>
                  <Text fontSize="sm" color={useSemanticToken('text.secondary')} textAlign="center" maxW="300px">
                    {caption || 'Generate a chart from your data using Claude Code'}
                  </Text>
                </VStack>
                {onGenerate && (
                  <Button
                    leftIcon={<FiBarChart2 />}
                    colorScheme="blue"
                    onClick={onGenerate}
                    size="md"
                  >
                    Generate Chart
                  </Button>
                )}
              </VStack>
            </Box>
          )}
        </Box>

        {/* Caption or Insights */}
        {(caption || metadata?.insights) && (
          <Box px={4} pb={4}>
            {caption && (
              <Text fontSize="sm" color={useSemanticToken('text.secondary')} mb={2}>
                {caption}
              </Text>
            )}
            {metadata?.insights && metadata.insights.length > 0 && (
              <VStack align="start" spacing={1}>
                <Text fontSize="xs" fontWeight="semibold" color={useSemanticToken('text.secondary')}>
                  KEY INSIGHTS:
                </Text>
                {metadata.insights.slice(0, 3).map((insight, idx) => (
                  <Text key={idx} fontSize="xs" color={useSemanticToken('text.secondary')}>
                    • {insight}
                  </Text>
                ))}
              </VStack>
            )}
          </Box>
        )}

        {/* Metadata Footer */}
        {metadata?.dimensions && (
          <Box
            px={4}
            py={2}
            borderTopWidth="1px"
            borderColor={borderColor}
            bg={useSemanticToken('surface.base')}
          >
            <Text fontSize="xs" color={useSemanticToken('text.secondary')}>
              {metadata.dimensions.width} × {metadata.dimensions.height}
              {metadata.dimensions.dpi && ` • ${metadata.dimensions.dpi} DPI`}
              {metadata.chartType && ` • ${metadata.chartType}`}
            </Text>
          </Box>
        )}
      </Box>

      {/* Full-size Modal */}
      <Modal isOpen={isOpen} onClose={onClose} size="6xl">
        <ModalOverlay />
        <ModalContent>
          <ModalCloseButton />
          <ModalBody p={0}>
            <Image
              src={imageSrc}
              alt={altText || title || 'Chart visualization'}
              width="100%"
              height="auto"
            />
          </ModalBody>
        </ModalContent>
      </Modal>
    </>
  );
}
