export type Phase0Subject = 'math' | 'reading' | 'analytical';

export interface Phase0DomainSeed {
  code: Phase0Subject;
  name: string;
  description: string;
  icon: string;
  color: string;
  sortOrder: number;
}

export interface Phase0SkillSeed {
  skillId: string;
  name: string;
  subject: Phase0Subject;
  minGrade: string;
  maxGrade: string;
  assessmentType: 'accuracy' | 'rubric' | 'ai_analysis';
  prerequisites: string[];
  description: string;
}

export interface Phase0ChildSeed {
  key: 'luca' | 'sofia';
  name: string;
  age: number;
  ageBand: 'middle' | 'tween';
  grade: '3' | '5';
  ownerIdEnvVar: string;
  readinessTargetCode: string;
  readinessTargetTitle: string;
  readinessDescription: string;
  readinessSkillsBySubject: {
    math: string[];
    reading: string[];
  };
  stretchSkillsBySubject: {
    math: string[];
    reading: string[];
  };
}

export const PHASE0_DOMAINS: Phase0DomainSeed[] = [
  {
    code: 'math',
    name: 'Mathematics',
    description: 'Number sense, operations, fractions, geometry, and problem solving.',
    icon: '🔢',
    color: '#3182CE',
    sortOrder: 1,
  },
  {
    code: 'reading',
    name: 'Reading & Comprehension',
    description: 'Phonics, fluency, vocabulary, and evidence-based comprehension.',
    icon: '📚',
    color: '#38A169',
    sortOrder: 2,
  },
  {
    code: 'analytical',
    name: 'Critical Thinking',
    description: 'Cross-subject reasoning, inference, evaluation, and metacognition.',
    icon: '🧠',
    color: '#D69E2E',
    sortOrder: 3,
  },
];

export const PHASE0_SKILLS: Phase0SkillSeed[] = [
  {
    skillId: 'math.number.count_20',
    name: 'Count & cardinality to 20',
    subject: 'math',
    minGrade: 'K',
    maxGrade: '1',
    assessmentType: 'accuracy',
    prerequisites: [],
    description: 'Count sets and understand one-to-one correspondence up to 20.',
  },
  {
    skillId: 'math.number.count_120',
    name: 'Count/read/write to 120',
    subject: 'math',
    minGrade: '1',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.count_20'],
    description: 'Read, write, and sequence whole numbers through 120.',
  },
  {
    skillId: 'math.number.place_value_100',
    name: 'Place value to 100',
    subject: 'math',
    minGrade: '1',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.count_120'],
    description: 'Use tens and ones to compose/decompose two-digit numbers.',
  },
  {
    skillId: 'math.number.compare_order',
    name: 'Compare & order numbers',
    subject: 'math',
    minGrade: '2',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.place_value_100'],
    description: 'Compare whole numbers using symbols and place-value reasoning.',
  },
  {
    skillId: 'math.number.place_value_1000',
    name: 'Place value to 1,000',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.place_value_100'],
    description: 'Understand hundreds, tens, and ones through 1,000.',
  },
  {
    skillId: 'math.number.place_value_10000',
    name: 'Place value to 10,000+',
    subject: 'math',
    minGrade: '4',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.place_value_1000'],
    description: 'Use place value and expanded form through ten-thousands.',
  },
  {
    skillId: 'math.number.round',
    name: 'Round to 10/100/1,000',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.place_value_1000'],
    description: 'Round numbers and justify rounding choices.',
  },
  {
    skillId: 'math.addsub.within_20',
    name: 'Add/subtract within 20',
    subject: 'math',
    minGrade: '1',
    maxGrade: '1',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.count_20'],
    description: 'Build fluency with basic addition and subtraction facts.',
  },
  {
    skillId: 'math.addsub.within_100',
    name: 'Add/subtract within 100',
    subject: 'math',
    minGrade: '2',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['math.addsub.within_20', 'math.number.place_value_100'],
    description: 'Use regrouping strategies for two-digit operations.',
  },
  {
    skillId: 'math.addsub.within_1000',
    name: 'Add/subtract within 1,000',
    subject: 'math',
    minGrade: '3',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['math.addsub.within_100', 'math.number.place_value_1000'],
    description: 'Solve three-digit operations using place-value strategies.',
  },
  {
    skillId: 'math.addsub.multi_digit',
    name: 'Multi-digit add/subtract',
    subject: 'math',
    minGrade: '4',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.addsub.within_1000'],
    description: 'Apply standard algorithms for larger whole numbers.',
  },
  {
    skillId: 'math.muldiv.concept',
    name: 'Multiplication concept (groups/arrays)',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['math.addsub.within_100'],
    description: 'Model multiplication as repeated addition, equal groups, and arrays.',
  },
  {
    skillId: 'math.muldiv.facts_10',
    name: 'Multiplication facts to 10x10',
    subject: 'math',
    minGrade: '3',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['math.muldiv.concept'],
    description: 'Build fact fluency with efficient strategies.',
  },
  {
    skillId: 'math.muldiv.division_basic',
    name: 'Division facts & remainders',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.muldiv.facts_10'],
    description: 'Connect multiplication/division and interpret remainders.',
  },
  {
    skillId: 'math.muldiv.multi_digit',
    name: 'Multi-digit multiplication',
    subject: 'math',
    minGrade: '4',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.muldiv.facts_10', 'math.number.place_value_1000'],
    description: 'Multiply larger numbers using place-value methods.',
  },
  {
    skillId: 'math.fractions.concept',
    name: 'Fraction concept (unit fractions)',
    subject: 'math',
    minGrade: '3',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['math.muldiv.concept'],
    description: 'Represent fractions as equal parts of a whole or set.',
  },
  {
    skillId: 'math.fractions.equivalence',
    name: 'Equivalent fractions',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.fractions.concept'],
    description: 'Generate and explain equivalent fraction relationships.',
  },
  {
    skillId: 'math.fractions.compare',
    name: 'Compare fractions',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.fractions.equivalence'],
    description: 'Compare fractions using visual and numerical reasoning.',
  },
  {
    skillId: 'math.fractions.addsub_like',
    name: 'Add/subtract fractions (like denominators)',
    subject: 'math',
    minGrade: '4',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.fractions.compare'],
    description: 'Compute and interpret fraction sums/differences with common denominators.',
  },
  {
    skillId: 'math.geometry.shapes_attributes',
    name: '2D/3D shapes & attributes',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['math.number.count_20'],
    description: 'Classify shapes by sides, angles, and dimensionality.',
  },
  {
    skillId: 'math.geometry.partition',
    name: 'Partition shapes into equal parts',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['math.geometry.shapes_attributes'],
    description: 'Partition shapes and connect parts to fractions.',
  },
  {
    skillId: 'math.measure.length_time',
    name: 'Measure length & time',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.count_120'],
    description: 'Measure using standard units and tell time to the minute.',
  },
  {
    skillId: 'math.measure.area_perimeter',
    name: 'Area & perimeter',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['math.muldiv.facts_10'],
    description: 'Find and compare area/perimeter of rectangles and related figures.',
  },
  {
    skillId: 'math.data.picture_bar',
    name: 'Read picture & bar graphs',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['math.number.count_120'],
    description: 'Interpret and compare categorical data displays.',
  },
  {
    skillId: 'math.reasoning.patterns',
    name: 'Number & shape patterns',
    subject: 'math',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['math.number.count_120'],
    description: 'Find, extend, and justify repeating or growing patterns.',
  },
  {
    skillId: 'math.reasoning.word_1step',
    name: 'One-step word problems',
    subject: 'math',
    minGrade: '2',
    maxGrade: '2',
    assessmentType: 'rubric',
    prerequisites: ['math.addsub.within_100'],
    description: 'Translate simple stories into operations with clear justification.',
  },
  {
    skillId: 'math.reasoning.word_2step',
    name: 'Two-step word problems',
    subject: 'math',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'rubric',
    prerequisites: ['math.reasoning.word_1step', 'math.muldiv.facts_10'],
    description: 'Solve multi-step problems and explain operation choice.',
  },
  {
    skillId: 'reading.phonics.letter_sounds',
    name: 'Phonemic awareness & letter-sounds',
    subject: 'reading',
    minGrade: 'K',
    maxGrade: 'K',
    assessmentType: 'accuracy',
    prerequisites: [],
    description: 'Connect letters with sounds and blend simple phonemes.',
  },
  {
    skillId: 'reading.phonics.cvc',
    name: 'Decode CVC words',
    subject: 'reading',
    minGrade: 'K',
    maxGrade: '1',
    assessmentType: 'accuracy',
    prerequisites: ['reading.phonics.letter_sounds'],
    description: 'Decode consonant-vowel-consonant words fluently.',
  },
  {
    skillId: 'reading.phonics.blends_digraphs',
    name: 'Decode blends & digraphs',
    subject: 'reading',
    minGrade: '1',
    maxGrade: '1',
    assessmentType: 'accuracy',
    prerequisites: ['reading.phonics.cvc'],
    description: 'Read words with blends and common digraphs.',
  },
  {
    skillId: 'reading.phonics.vowel_teams',
    name: 'Long vowels & vowel teams',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['reading.phonics.blends_digraphs'],
    description: 'Decode long-vowel patterns and vowel teams.',
  },
  {
    skillId: 'reading.phonics.multisyllable',
    name: 'Decode multisyllabic words',
    subject: 'reading',
    minGrade: '3',
    maxGrade: '3',
    assessmentType: 'accuracy',
    prerequisites: ['reading.phonics.vowel_teams'],
    description: 'Use syllable patterns and morphology to decode longer words.',
  },
  {
    skillId: 'reading.fluency.accuracy_rate',
    name: 'Reading fluency (accuracy & pace)',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'ai_analysis',
    prerequisites: ['reading.phonics.vowel_teams'],
    description: 'Read connected text accurately and at an age-appropriate pace.',
  },
  {
    skillId: 'reading.fluency.expression',
    name: 'Reading fluency (expression)',
    subject: 'reading',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'ai_analysis',
    prerequisites: ['reading.fluency.accuracy_rate'],
    description: 'Use prosody and expression to convey meaning while reading.',
  },
  {
    skillId: 'reading.vocab.context_clues',
    name: 'Use context clues',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['reading.phonics.cvc'],
    description: 'Infer word meaning from nearby text clues.',
  },
  {
    skillId: 'reading.vocab.affixes_roots',
    name: 'Use affixes and roots',
    subject: 'reading',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'accuracy',
    prerequisites: ['reading.phonics.multisyllable'],
    description: 'Use prefixes, suffixes, and roots to decode and define words.',
  },
  {
    skillId: 'reading.vocab.academic',
    name: 'Academic/domain vocabulary',
    subject: 'reading',
    minGrade: '4',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: ['reading.vocab.affixes_roots'],
    description: 'Understand and use subject-specific academic vocabulary.',
  },
  {
    skillId: 'reading.comp.retell_sequence',
    name: 'Retell and sequence events',
    subject: 'reading',
    minGrade: '1',
    maxGrade: '2',
    assessmentType: 'rubric',
    prerequisites: ['reading.phonics.cvc'],
    description: 'Retell stories and sequence key events accurately.',
  },
  {
    skillId: 'reading.comp.literal',
    name: 'Literal comprehension',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '2',
    assessmentType: 'accuracy',
    prerequisites: ['reading.comp.retell_sequence'],
    description: 'Find explicit information and answer direct questions.',
  },
  {
    skillId: 'reading.comp.main_idea',
    name: 'Main idea and key details',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['reading.comp.retell_sequence', 'reading.fluency.accuracy_rate'],
    description: 'Identify central ideas and supporting details in text.',
  },
  {
    skillId: 'reading.comp.inference',
    name: 'Inference',
    subject: 'reading',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'ai_analysis',
    prerequisites: ['reading.comp.main_idea'],
    description: 'Infer meaning using clues plus prior knowledge.',
  },
  {
    skillId: 'reading.comp.text_structure',
    name: 'Text structure',
    subject: 'reading',
    minGrade: '3',
    maxGrade: '4',
    assessmentType: 'rubric',
    prerequisites: ['reading.comp.main_idea'],
    description: 'Analyze compare/contrast, cause/effect, and problem/solution structures.',
  },
  {
    skillId: 'reading.comp.authors_purpose',
    name: "Author's purpose & point of view",
    subject: 'reading',
    minGrade: '4',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: ['reading.comp.inference'],
    description: "Explain why an author wrote a text and from what perspective.",
  },
  {
    skillId: 'reading.comp.evaluate_evidence',
    name: 'Evaluate evidence and claims',
    subject: 'reading',
    minGrade: '4',
    maxGrade: '5',
    assessmentType: 'ai_analysis',
    prerequisites: ['reading.comp.inference', 'reading.comp.text_structure'],
    description: 'Support claims with textual evidence and distinguish fact/opinion.',
  },
  {
    skillId: 'reading.comp.theme',
    name: 'Theme / central message',
    subject: 'reading',
    minGrade: '4',
    maxGrade: '5',
    assessmentType: 'ai_analysis',
    prerequisites: ['reading.comp.inference'],
    description: 'Determine and justify themes in literary and informational texts.',
  },
  {
    skillId: 'reading.lit.story_elements',
    name: 'Story elements',
    subject: 'reading',
    minGrade: '2',
    maxGrade: '3',
    assessmentType: 'rubric',
    prerequisites: ['reading.comp.retell_sequence'],
    description: 'Analyze character, setting, and plot development.',
  },
  {
    skillId: 'reading.lit.figurative',
    name: 'Figurative language',
    subject: 'reading',
    minGrade: '4',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: ['reading.lit.story_elements', 'reading.vocab.affixes_roots'],
    description: 'Interpret similes, metaphors, idioms, and figurative expressions.',
  },
  {
    skillId: 'analytical.compare_classify',
    name: 'Compare and classify',
    subject: 'analytical',
    minGrade: '2',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: [],
    description: 'Compare attributes and classify ideas with explicit criteria.',
  },
  {
    skillId: 'analytical.cause_effect',
    name: 'Cause and effect reasoning',
    subject: 'analytical',
    minGrade: '2',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: [],
    description: 'Explain sequence and causal links between events or actions.',
  },
  {
    skillId: 'analytical.infer_evidence',
    name: 'Inference with evidence',
    subject: 'analytical',
    minGrade: '2',
    maxGrade: '5',
    assessmentType: 'ai_analysis',
    prerequisites: [],
    description: 'Draw conclusions and justify them with evidence.',
  },
  {
    skillId: 'analytical.evaluate',
    name: 'Evaluate reasoning',
    subject: 'analytical',
    minGrade: '3',
    maxGrade: '5',
    assessmentType: 'ai_analysis',
    prerequisites: ['analytical.infer_evidence'],
    description: 'Check claims for quality, coherence, and supporting evidence.',
  },
  {
    skillId: 'analytical.patterns',
    name: 'Pattern detection and extension',
    subject: 'analytical',
    minGrade: '2',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: [],
    description: 'Detect patterns in data, text, and structures, then extend them.',
  },
  {
    skillId: 'analytical.metacognition',
    name: 'Metacognitive reflection',
    subject: 'analytical',
    minGrade: '2',
    maxGrade: '5',
    assessmentType: 'rubric',
    prerequisites: [],
    description: 'Describe strategies used and reflect on what to improve next.',
  },
];

export const PHASE0_CHILDREN: Phase0ChildSeed[] = [
  {
    key: 'luca',
    name: 'Luca',
    age: 8,
    ageBand: 'middle',
    grade: '3',
    ownerIdEnvVar: 'LUCA_OWNER_ID',
    readinessTargetCode: 'phase0_luca_grade3_readiness',
    readinessTargetTitle: 'Luca Grade 3 Readiness',
    readinessDescription: 'Readiness frontier to enter grade 3 (master end-of-grade-2 skills).',
    readinessSkillsBySubject: {
      math: [
        'math.number.count_120',
        'math.number.place_value_100',
        'math.number.compare_order',
        'math.addsub.within_20',
        'math.addsub.within_100',
        'math.muldiv.concept',
        'math.geometry.shapes_attributes',
        'math.geometry.partition',
        'math.measure.length_time',
        'math.data.picture_bar',
        'math.reasoning.patterns',
        'math.reasoning.word_1step',
      ],
      reading: [
        'reading.phonics.vowel_teams',
        'reading.fluency.accuracy_rate',
        'reading.vocab.context_clues',
        'reading.comp.retell_sequence',
        'reading.comp.literal',
        'reading.comp.main_idea',
        'reading.lit.story_elements',
      ],
    },
    stretchSkillsBySubject: {
      math: ['math.number.place_value_1000', 'math.addsub.within_1000', 'math.fractions.concept'],
      reading: ['reading.phonics.multisyllable', 'reading.comp.inference'],
    },
  },
  {
    key: 'sofia',
    name: 'Sofia',
    age: 10,
    ageBand: 'tween',
    grade: '5',
    ownerIdEnvVar: 'SOFIA_OWNER_ID',
    readinessTargetCode: 'phase0_sofia_grade5_readiness',
    readinessTargetTitle: 'Sofia Grade 5 Readiness',
    readinessDescription: 'Readiness frontier to enter grade 5 (master end-of-grade-4 skills).',
    readinessSkillsBySubject: {
      math: [
        'math.number.place_value_10000',
        'math.number.round',
        'math.addsub.multi_digit',
        'math.muldiv.facts_10',
        'math.muldiv.multi_digit',
        'math.muldiv.division_basic',
        'math.fractions.equivalence',
        'math.fractions.compare',
        'math.fractions.addsub_like',
        'math.measure.area_perimeter',
        'math.reasoning.word_2step',
      ],
      reading: [
        'reading.phonics.multisyllable',
        'reading.fluency.expression',
        'reading.vocab.affixes_roots',
        'reading.vocab.academic',
        'reading.comp.inference',
        'reading.comp.text_structure',
        'reading.comp.authors_purpose',
        'reading.comp.evaluate_evidence',
        'reading.comp.theme',
        'reading.lit.figurative',
      ],
    },
    stretchSkillsBySubject: {
      math: [],
      reading: [],
    },
  },
];
