/**
 * Navigation Configuration
 * Central configuration for all dashboard navigation items
 * Organized by: AI Productivity > Administrative > Infrastructure
 */

import {
  HomeIcon,
  ServerIcon,
  DocumentTextIcon,
  CpuChipIcon,
  BoltIcon,
  ShieldCheckIcon,
  BookOpenIcon,
  PuzzlePieceIcon,
  CogIcon,
  RocketLaunchIcon,
  UserGroupIcon,
  CommandLineIcon,
  ChartBarIcon,
  EyeIcon,
  ClipboardDocumentCheckIcon,
  AcademicCapIcon,
  MicrophoneIcon,
  RadioIcon,
  ChartPieIcon,
  PhotoIcon,
  MagnifyingGlassIcon,
  EnvelopeIcon,
  CheckCircleIcon,
  CalendarIcon,
  LightBulbIcon,
} from '@heroicons/react/24/outline';
import { Cog6ToothIcon, ChatBubbleLeftRightIcon } from '@heroicons/react/24/outline';
import type { NavItem } from '@/components/layout/GlassSidebar';

export const navigationItems: NavItem[] = [
  // ===== AI PRODUCTIVITY SECTION =====
  {
    label: 'Home',
    path: '/',
    icon: HomeIcon,
    domain: 'dashboard',
  },
  {
    label: 'Tesla Dashboard',
    path: '/tesla',
    icon: BoltIcon,
    domain: 'dashboard',
    badge: 'Car',
    badgeColorScheme: 'green',
  },
  {
    label: 'Personal AI',
    path: '/openclaw',
    icon: CpuChipIcon,
    domain: 'aiSystems',
    badge: 'OpenClaw',
    badgeColorScheme: 'blue',
    children: [
      {
        label: 'Agent Chat',
        path: '/openclaw',
        icon: ChatBubbleLeftRightIcon,
        badge: 'OpenClaw',
        badgeColorScheme: 'blue',
      },
      {
        label: 'Personal Context',
        path: '/personal-context',
        icon: UserGroupIcon,
        badge: 'PIC',
        badgeColorScheme: 'purple',
      },
      {
        label: 'Atlas Insights',
        path: '/atlas-insights',
        icon: LightBulbIcon,
        badge: 'Atlas',
        badgeColorScheme: 'yellow',
      },
    ],
  },
  {
    label: 'Workspace',
    path: '/workspace',
    icon: BookOpenIcon,
    domain: 'productivity',
    badge: 'Notion 3.0',
    badgeColorScheme: 'purple',
  },
  {
    label: 'Email Agent',
    path: '/email',
    icon: EnvelopeIcon,
    domain: 'productivity',
    badge: 'GraphRAG',
    badgeColorScheme: 'purple',
  },
  {
    label: 'Calendar',
    path: '/calendar',
    icon: CalendarIcon,
    domain: 'productivity',
    badge: 'AI Sync',
    badgeColorScheme: 'blue',
  },

  {
    label: 'Image Studio',
    path: '/image-studio',
    icon: PhotoIcon,
    domain: 'productivity',
    badge: 'Beta',
    badgeColorScheme: 'pink',
  },
  {
    label: 'Podcast Studio',
    path: '/podcast-studio',
    icon: RadioIcon,
    domain: 'productivity',
    badge: 'New',
    badgeColorScheme: 'purple',
  },
  {
    label: 'Voice Studio',
    path: '/voice-studio',
    icon: MicrophoneIcon,
    domain: 'productivity',
    badge: 'Qwen3',
    badgeColorScheme: 'cyan',
  },
  {
    label: 'AI-Research',
    path: '/ai-research',
    icon: AcademicCapIcon,
    domain: 'research',
    badge: 'Premium',
    badgeColorScheme: 'orange',
  },
  {
    label: 'AI & ML Ops',
    path: '#',
    icon: CpuChipIcon,
    domain: 'aiSystems',
    children: [
      {
        label: 'ML Training Hub',
        path: '/ml-training',
        icon: ChartBarIcon,
        badge: 'Training',
        badgeColorScheme: 'purple',
      },
    ],
  },
  {
    label: 'Agentic Workflows',
    path: '/agentic-workflows',
    icon: BoltIcon,
    domain: 'aiSystems',
  },
  {
    label: 'Knowledge Base',
    path: '#',
    icon: BookOpenIcon,
    domain: 'knowledge',
    children: [
      {
        label: 'Knowledge Hub',
        path: '/knowledge',
        icon: BookOpenIcon,
        badge: 'Unified',
        badgeColorScheme: 'blue',
      },
      {
        label: 'Graph View',
        path: '/knowledge?tab=graph',
        icon: ChartBarIcon,
        badge: '3D',
        badgeColorScheme: 'purple',
      },
      {
        label: 'Agents',
        path: '/knowledge?tab=agents',
        icon: CpuChipIcon,
        badge: 'Live',
        badgeColorScheme: 'green',
      },
      {
        label: 'Documents',
        path: '/knowledge/documents',
        icon: DocumentTextIcon,
      },
      {
        label: 'Database Management',
        path: '/database',
        icon: CommandLineIcon,
        badge: 'CLI',
        badgeColorScheme: 'blue',
      },
      {
        label: 'IDE Memory',
        path: '/ide-memory',
        icon: CpuChipIcon,
        badge: 'Enhanced',
        badgeColorScheme: 'purple',
      },
      {
        label: 'Advanced Graph',
        path: '/knowledge-graph',
        icon: ChartPieIcon,
        badge: 'Full',
        badgeColorScheme: 'orange',
      },
    ],
  },

  // ===== ADMINISTRATIVE SECTION =====
  {
    label: 'Family Hub',
    path: '/family',
    icon: UserGroupIcon,
    domain: 'admin',
    badge: 'Parental',
    badgeColorScheme: 'green',
  },
  {
    label: 'Approvals',
    path: '/approvals',
    icon: CheckCircleIcon,
    domain: 'admin',
    badge: 'Parental',
    badgeColorScheme: 'blue',
  },
  {
    label: 'Admin Panel',
    path: '#',
    icon: ShieldCheckIcon,
    domain: 'admin',
    children: [
      {
        label: 'Admin Dashboard',
        path: '/admin',
        icon: HomeIcon,
        badge: 'Control',
        badgeColorScheme: 'orange',
      },
      {
        label: 'User Management',
        path: '/admin/users',
        icon: UserGroupIcon,
      },
      {
        label: 'Tenant Management',
        path: '/admin/tenants',
        icon: ServerIcon,
      },
      {
        label: 'Family Management',
        path: '/admin/family',
        icon: UserGroupIcon,
        badge: 'Parental',
        badgeColorScheme: 'green',
      },
      {
        label: 'User Features',
        path: '/admin/user-features',
        icon: CogIcon,
      },
      {
        label: 'Agentic Control',
        path: '/agentic-control',
        icon: Cog6ToothIcon,
        badge: 'Agents',
        badgeColorScheme: 'green',
      },
      {
        label: 'Quotas',
        path: '/admin/quotas',
        icon: ChartPieIcon,
      },
    ],
  },
  {
    label: 'Projects',
    path: '#',
    icon: PuzzlePieceIcon,
    domain: 'projects',
    children: [
      {
        label: 'All Projects',
        path: '/ecosystem/projects',
        icon: EyeIcon,
      },
      {
        label: 'Onboarding',
        path: '/ecosystem/onboarding',
        icon: RocketLaunchIcon,
      },
    ],
  },

  // ===== INFRASTRUCTURE SECTION =====
  {
    label: 'Infrastructure',
    path: '#',
    icon: ServerIcon,
    domain: 'infrastructure',
    children: [
      {
        label: 'AHIS',
        path: '/infrastructure/ahis',
        icon: ServerIcon,
        badge: 'Core',
        badgeColorScheme: 'blue',
      },
      {
        label: 'Agent Registry',
        path: '/agent-registry',
        icon: UserGroupIcon,
        badge: 'Active',
        badgeColorScheme: 'green',
      },
      {
        label: 'Port Registry',
        path: '/infrastructure/ports',
        icon: CommandLineIcon,
      },
      {
        label: 'Kubernetes',
        path: '/infrastructure/kubernetes',
        icon: ServerIcon,
        badge: 'Live',
        badgeColorScheme: 'green',
      },
      {
        label: 'AI Gateway',
        path: '/infrastructure/ai-gateway',
        icon: CpuChipIcon,
        badge: 'Routing',
        badgeColorScheme: 'blue',
      },
      {
        label: 'AI Inferencing',
        path: '/ai-inferencing',
        icon: BoltIcon,
        badge: 'API Keys',
        badgeColorScheme: 'green',
      },
      {
        label: 'Nova Cache',
        path: '/nova-cache',
        icon: BoltIcon,
        badge: 'AI',
        badgeColorScheme: 'purple',
      },
      {
        label: 'OpenClaw Gateway',
        path: '/infrastructure/openclaw',
        icon: CommandLineIcon,
        badge: 'Agent',
        badgeColorScheme: 'orange',
      },
      {
        label: 'Agent Control',
        path: '/openclaw-control',
        icon: BoltIcon,
        badge: 'Live',
        badgeColorScheme: 'green',
      },
      {
        label: 'Browser Oversight',
        path: '/openclaw-browser-oversight',
        icon: EyeIcon,
        badge: 'New',
        badgeColorScheme: 'blue',
        isNew: true,
      },
      {
        label: 'Tickets',
        path: '/infrastructure/tickets',
        icon: ClipboardDocumentCheckIcon,
        badge: 'New',
        badgeColorScheme: 'orange',
        isNew: true,
      },
    ],
  },
  {
    label: 'Monitoring',
    path: '/monitoring',
    icon: ChartBarIcon,
    domain: 'infrastructure',
  },
  {
    label: 'System Backup',
    path: '/system-backup',
    icon: ServerIcon,
    domain: 'infrastructure',
    badge: 'Live',
    badgeColorScheme: 'green',
  },
  {
    label: 'Platform Config',
    path: '/platforms/config',
    icon: CogIcon,
    domain: 'infrastructure',
  },
  {
    label: 'Security',
    path: '#',
    icon: ShieldCheckIcon,
    domain: 'infrastructure',
    badge: 'Zero Trust',
    badgeColorScheme: 'green',
    children: [
      {
        label: 'Security Dashboard',
        path: '/security',
        icon: ShieldCheckIcon,
        badge: 'Live',
        badgeColorScheme: 'green',
      },
      {
        label: 'Approvals',
        path: '/security/approvals',
        icon: CheckCircleIcon,
        badge: 'HITL',
        badgeColorScheme: 'blue',
      },
      {
        label: 'Audit Log',
        path: '/security/audit-log',
        icon: DocumentTextIcon,
      },
      {
        label: 'Security Settings',
        path: '/security/settings',
        icon: CogIcon,
      },
      {
        label: 'System Health',
        path: '/security/health',
        icon: ChartBarIcon,
        badge: 'Live',
        badgeColorScheme: 'green',
      },
    ],
  },
  {
    label: 'Compliance',
    path: '/compliance',
    icon: ClipboardDocumentCheckIcon,
    domain: 'infrastructure',
    badge: 'Required',
    badgeColorScheme: 'red',
  },
  {
    label: 'Testing Suite',
    path: '/testing',
    icon: ClipboardDocumentCheckIcon,
    domain: 'infrastructure',
    badge: 'Auto',
    badgeColorScheme: 'blue',
  },
];
