/**
 * Nova Labels — mirrors NovaLabels.swift strings for the dashboard UI.
 * Keep in sync with Shared/Design/NovaLabels.swift in the iOS repo.
 */

export const novaLabels = {
  thinkingCard: {
    headerLive:     "Working on it\u2026",
    headerDone:     "Done",
    thinkingLive:   "Thinking\u2026",
    thinkingDone:   "Done",
    seeFullThought: "See full thought process",
    seeThought:     "See thought process",
    sheetTitleLive: "Nova is thinking\u2026",
    sheetTitleDone: "Thought process",
  },
  validationPhase: {
    ready:              "Ready",
    thinking:           "Thinking\u2026",
    checking:           "Checking\u2026",
    done:               "Done",
    cardHeader:         "Working on it",
    initialTake:        "Initial take",
    draftingResponse:   "Drafting a response\u2026",
    checkingWork:       "Checking my work\u2026",
    respondingDirectly: "Answered from knowledge",
    directDetail:       "No lookups needed",
    doneChecking:       "Done checking",
  },
  validationResult: {
    verified:          "Answer verified",
    refined:           "Answer refined",
    enriched:          "Answer enriched",
    respondedDirectly: "Answered from knowledge",
    wentWrong:         "Something went wrong",
    encounteredError:  "Encountered an error",
  },
  toolNames: {
    web_search:            "Searching the web\u2026",
    search_web:            "Searching the web\u2026",
    tavily_search:         "Searching the web\u2026",
    search:                "Searching the web\u2026",
    perplexity_search:     "Searching the web\u2026",
    brave_search:          "Searching the web\u2026",
    google_search:         "Searching the web\u2026",
    searxng:               "Searching the web\u2026",
    serper:                "Searching the web\u2026",
    deep_research:         "Researching in depth\u2026",
    research:              "Researching in depth\u2026",
    browse_url:            "Reading a webpage\u2026",
    read_url:              "Reading a webpage\u2026",
    fetch_url:             "Reading a webpage\u2026",
    scrape:                "Reading page content\u2026",
    web_scrape:            "Reading page content\u2026",
    memory_search:         "Searching my memory\u2026",
    search_memory:         "Searching my memory\u2026",
    memory_store:          "Saving to memory\u2026",
    store_memory:          "Saving to memory\u2026",
    save_memory:           "Saving to memory\u2026",
    memory_delete:         "Forgetting a memory\u2026",
    forget_memory:         "Forgetting a memory\u2026",
    knowledge_graph:       "Searching knowledge base\u2026",
    kg_query:              "Searching knowledge base\u2026",
    rag_search:            "Searching your documents\u2026",
    vector_search:         "Searching your documents\u2026",
    get_calendar:          "Checking your calendar\u2026",
    calendar_events:       "Checking your calendar\u2026",
    check_calendar:        "Checking your calendar\u2026",
    list_events:           "Checking your calendar\u2026",
    create_event:          "Adding a calendar event\u2026",
    add_event:             "Adding a calendar event\u2026",
    schedule_event:        "Adding a calendar event\u2026",
    update_event:          "Updating calendar event\u2026",
    edit_event:            "Updating calendar event\u2026",
    delete_event:          "Removing calendar event\u2026",
    remove_event:          "Removing calendar event\u2026",
    get_emails:            "Reading your emails\u2026",
    fetch_emails:          "Reading your emails\u2026",
    list_emails:           "Reading your emails\u2026",
    read_email:            "Reading your emails\u2026",
    send_email:            "Drafting an email\u2026",
    draft_email:           "Drafting an email\u2026",
    compose_email:         "Drafting an email\u2026",
    reply_email:           "Replying to email\u2026",
    create_workspace:      "Creating a workspace page\u2026",
    workspace_create:      "Creating a workspace page\u2026",
    create_page:           "Creating a workspace page\u2026",
    workspace_create_page: "Creating a workspace page\u2026",
    update_workspace:      "Updating a workspace page\u2026",
    edit_workspace:        "Updating a workspace page\u2026",
    manage_workspace:      "Updating a workspace page\u2026",
    workspace_update:      "Updating a workspace page\u2026",
    read_workspace:        "Reading a workspace page\u2026",
    get_workspace:         "Reading a workspace page\u2026",
    workspace_read:        "Reading a workspace page\u2026",
    workspace_get:         "Reading a workspace page\u2026",
    manage_task_plan:      "Updating the task planner\u2026",
    update_task_plan:      "Updating the task planner\u2026",
    create_task_plan:      "Updating the task planner\u2026",
    task_plan:             "Updating the task planner\u2026",
    manage_note:           "Saving a note\u2026",
    update_note:           "Saving a note\u2026",
    create_note:           "Saving a note\u2026",
    note:                  "Saving a note\u2026",
    manage_page:           "Editing a workspace page\u2026",
    update_page:           "Editing a workspace page\u2026",
    edit_page:             "Editing a workspace page\u2026",
    code_generate:         "Writing code\u2026",
    generate_code:         "Writing code\u2026",
    write_code:            "Writing code\u2026",
    code_execute:          "Running code\u2026",
    run_code:              "Running code\u2026",
    execute_code:          "Running code\u2026",
    homekit_control:       "Controlling your smart home\u2026",
    smart_home:            "Controlling your smart home\u2026",
    home_control:          "Controlling your smart home\u2026",
    health_data:           "Reading health data\u2026",
    get_health:            "Reading health data\u2026",
    healthkit:             "Reading health data\u2026",
    create_approval:       "Requesting your approval\u2026",
    request_approval:      "Requesting your approval\u2026",
    get_approvals:         "Checking pending approvals\u2026",
    list_approvals:        "Checking pending approvals\u2026",
    check_approvals:       "Checking pending approvals\u2026",
    get_weather:           "Checking the weather\u2026",
    weather:               "Checking the weather\u2026",
    weather_lookup:        "Checking the weather\u2026",
    get_location:          "Finding your location\u2026",
    location:              "Finding your location\u2026",
    locate:                "Finding your location\u2026",
    delegate:              "Routing to agent\u2026",
    openclaw_delegate:     "Routing to agent\u2026",
    route_to_agent:        "Routing to agent\u2026",
  } as Record<string, string>,
} as const;

/** Resolve a backend tool name to a user-facing label (mirrors NovaLabels.toolLabel). */
export function toolLabel(raw: string): string {
  const key = raw.toLowerCase().trim();
  const known = novaLabels.toolNames[key];
  if (known) return known;
  return raw.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) + "\u2026";
}
